Auth middleware/49
Fargo-praktikum/game pull request #38
Opened 2021-06-18 04:26 UTC by RGlendon

Добавил проверку авторизации на ssr, для этого пришлось настраивать https и в etc/hosts вам нужно добавить запись `127.0.0.1 localhost.ya-praktikum.tech`, можно конечно скрипт добавить для этого, но пока вручную.
После добавления https перестал sw работать корректно, видимо с сертификатами в папке devCert что-то не так. Также при мерже с main docker не запускается (нужен файл dev.env), поэтому в package.json переименовал на время этот скрипт

2021-06-21 20:43 UTC, Grumaks requested changes
Посмотрел, замечания в комментах.
Жду, когда проверишь работоспособность и возможность дебага sw

2021-06-21 20:43 UTC, Grumaks commented on configs/hosts.json
> +    "host": "localhost.ya-praktikum.tech",
для однообразия лучше local.....

2021-06-21 20:43 UTC, Grumaks commented on server/helpers/network.ts
> +    for (const name of Object.keys(nets)) {
такое лучше обходить через entries, тогда не придется использовать !

2021-06-21 20:43 UTC, Grumaks commented on server/helpers/startApp.ts
> +// import { homedir } from "os";
если не нужно, стоит убрать

2021-06-21 20:43 UTC, Grumaks commented on server/middlewares/serverAuthMiddleware.ts
> +    const condition = cookiesCount === 0 && isLoginUrl;
нужно какое-то более осознанное имя

2021-06-21 20:43 UTC, Grumaks commented on server/middlewares/serverAuthMiddleware.ts
> +        .then(response => {
ао всем проекте используем async/await мб и тут тоже стоит?

2021-06-21 20:43 UTC, Grumaks commented on src/hooks/storeHooks.ts
> +// Use throughout your server instead of plain `useDispatch` and `useSelector`
теперь в комментарии неправда, там нужно именно app

2021-06-23 00:51 UTC, RGlendon commented on server/middlewares/serverAuthMiddleware.ts
> +        .then(response => {
тогда мидлварю нужно делать async, эта функция возвращает промиc, не очень хочется еще один модуль ставить middleware-async

2021-06-23 13:30 UTC, Grumaks approved these changes

2021-06-24 16:13 UTC, merged